name: 'Ruby Bundler Audit Action'
description: 'GitHub Action for running bundler-audit'
author: 'Alejandro Cavallo <alejandro.cavallo@stoneitcloud.com>'
runs:
  using: 'docker'
  image: 'Dockerfile'
env:
  GITHUB_TOKEN: secrets.GITHUB_TOKEN
branding:
  icon: 'shield'
  color: 'gray-dark'
